application: myaivalet
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css

- url: /css/ie
  static_dir: css/ie

- url: /css/ie/images
  static_dir: css/ie/images

- url: /css/images
  static_dir: css/images

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts

- url: /AddCommand
  script: AddCommand.application

- url: /Add.*
  script: Add.application

- url: /Process.*
  script: Process.application

- url: /index
  script: index.application

- url: /.*
  script: index.application

libraries:

- name: webapp2
  version: latest

- name: jinja2
  version: latest
